InfoSec Page and Replacement of undraw images
CougarCS/CougarCS-Client pull request #577
Opened 2023-11-01 23:30 UTC by DylanMiller765

## What type of PR is this? (check all applicable)

- [X] ♻️ Refactor
- [X] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR adds an InfoSec page and replaces the undraw images with more fitting pictures.

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

![About Us Page](https://github.com/CougarCS/CougarCS-Client/assets/136383534/7c3ad039-b7a3-4732-815c-99abcb639901)
![InfoSec Page](https://github.com/CougarCS/CougarCS-Client/assets/136383534/70fa455c-4f26-489c-9403-cca9f25ce360)
![Tutoring Page](https://github.com/CougarCS/CougarCS-Client/assets/136383534/047f78d2-3e9b-4de7-97a0-f402ac700aa6)

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 docs
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

2023-11-01 23:34 UTC, DylanMiller765 commented
Should the logo on the About Us page be moved to the right? For the Info Sec page is there a rough idea of what should be on it? I checked the Figma and didn't see a page for it.

2023-11-02 03:37 UTC, Brodypen requested changes

2023-11-02 03:37 UTC, Brodypen commented on src/components/Navbar/Navbar.js
> +					<ActiveListItem url='/InfoSec' name='InfoSec' />
url should be /infosec to be consistent with current style

2023-11-02 03:37 UTC, Brodypen commented on src/pages/InfoSec/InfoSec.js
> +	url: 'https://cougarcs.com/web-dev',
change to be accurate to current site.
desc: 'Learn more about CougarCS Info-sec'
url: 'https://cougarcs.com/infosec'

2023-11-02 03:37 UTC, Brodypen commented on src/App.js
> +						<Route path='/InfoSec' element={<InfoSec />} />
move route between tutoring and gallery/event

2023-11-02 03:37 UTC, Brodypen commented on src/components/Navbar/Navbar.js
> +					<ActiveListItem url='/InfoSec' name='InfoSec' />
info sec should be before contact us in the navbar.

2023-11-02 03:37 UTC, Brodypen commented on src/pages/InfoSec/InfoSec.js
> +								to sure what the vision is here
look at webdev/tutoring for help on making this page to look better.

Discord button should link to info sec discord.

2023-11-06 02:04 UTC, Brodypen approved these changes

2023-11-06 02:04 UTC, merged